name: Block PR Merge on Checklist

# on comment event
on:
  issue_comment:
    types: [created, edited, deleted]

permissions:
  contents: read

jobs:
  list-comments:
    permissions:
      pull-requests: write
      statuses: write # Allow to modfiy commit status
    runs-on: ubuntu-latest
    steps:
      - name: List Github Event
        run: |
          echo "GitHub Event Details:"
          echo "${{ toJSON(github.event) }}"
          echo "\nEvent Name: ${{ github.event_name }}"
          echo "\nEvent Path: $GITHUB_EVENT_PATH"
          cat $GITHUB_EVENT_PATH
